[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.217"
warp = "0.3.7"
tokio = { version = "1", features=["full"] }
tokio-macros = { version = "0.2.0-alpha.6" }

